db.type=mysql

mysql.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Europe/Moscow&allowPublicKeyRetrieval=true
mysql.user=root
mysql.password=0000

mssql.url=jdbc:sqlserver://localhost:1433;databaseName=mydb;integratedSecurity=true;trustServerCertificate=true;encrypt=false;